package lan

import (
	"bufio"
	"bytes"
	_ "embed"
	"encoding/csv"
	"encoding/json"
	"io"
	"net/netip"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/BurntSushi/toml"

	"github.com/zebadrabbit/sitrep/internal/modules/ports"
)

// oui.csv is generated by scripts/gen-oui.py from the IEEE MA-L registry,
// filtered to the vendors that turn up on a home or lab LAN.
//
// ponytail: MA-L (24-bit) only, so a vendor with a 28- or 36-bit block shows
// its raw prefix instead. Add mam.csv/oui36.csv to the generator if that ever
// matters; the user override in lan.toml covers the one-off case today.
//
//go:embed oui.csv
var ouiCSV []byte

// Neighbor is one raw row of the kernel's neighbor table, before folding.
type Neighbor struct {
	IP    string
	MAC   string
	Iface string
	State string
}

// Host is one device, folded across every address sharing its MAC.
type Host struct {
	MAC     string   `json:"mac,omitempty"`
	IP      string   `json:"ip"`
	Extra   []string `json:"extra,omitempty"` // other addresses on the same MAC
	Iface   string   `json:"iface"`
	Subnet  string   `json:"subnet,omitempty"`
	Vendor  string   `json:"vendor,omitempty"`
	Name    string   `json:"name,omitempty"` // from the user's lan.toml
	State   string   `json:"state"`          // reachable | stale | failed | …
	Random  bool     `json:"random"`         // locally administered MAC
	Virtual bool     `json:"virtual"`        // reached over a bridge/veth/tunnel, not a NIC
	Shared  bool     `json:"shared_mac"`     // another address answers on this MAC too
	Gateway bool     `json:"gateway"`
	// In are our local ports this host has connected to; Out are its ports we
	// have connected to. Both from the socket table, nothing is sent.
	In  []int `json:"in,omitempty"`
	Out []int `json:"out,omitempty"`
}

// Subnet is one link-scope route: the CIDR and the interface serving it.
type Subnet struct {
	CIDR  string `json:"cidr"`
	Iface string `json:"iface"`
}

type ipNeigh struct {
	Dst    string   `json:"dst"`
	Dev    string   `json:"dev"`
	LLAddr string   `json:"lladdr"`
	State  []string `json:"state"`
}

// ParseNeigh decodes `ip -j neigh`. A malformed document yields no rows
// rather than an error; the collector falls back to /proc/net/arp.
func ParseNeigh(out []byte) []Neighbor {
	var rows []ipNeigh
	if json.Unmarshal(out, &rows) != nil {
		return nil
	}
	ns := make([]Neighbor, 0, len(rows))
	for _, r := range rows {
		if r.Dst == "" {
			continue
		}
		ns = append(ns, Neighbor{
			IP:    r.Dst,
			MAC:   strings.ToLower(r.LLAddr),
			Iface: r.Dev,
			State: strings.ToLower(strings.Join(r.State, " ")),
		})
	}
	return ns
}

// ParseProcARP reads /proc/net/arp, the fallback when iproute2 is absent
// (invariant 4). IPv4 only, and it has no state beyond the incomplete flag.
func ParseProcARP(out []byte) []Neighbor {
	var ns []Neighbor
	sc := bufio.NewScanner(bytes.NewReader(out))
	for sc.Scan() {
		f := strings.Fields(sc.Text())
		// IP address  HW type  Flags  HW address  Mask  Device
		if len(f) < 6 || f[0] == "IP" {
			continue
		}
		n := Neighbor{IP: f[0], MAC: strings.ToLower(f[3]), Iface: f[5], State: "stale"}
		if f[2] == "0x0" || n.MAC == "00:00:00:00:00:00" {
			n.MAC, n.State = "", "failed"
		}
		ns = append(ns, n)
	}
	return ns
}

type ipRoute struct {
	Dst   string `json:"dst"`
	Dev   string `json:"dev"`
	Scope string `json:"scope"`
}

// ParseLinkSubnets pulls the on-link CIDRs out of `ip -j route`. These are
// what group the host table; anything outside them lands under its interface.
func ParseLinkSubnets(out []byte) []Subnet {
	var rows []ipRoute
	if json.Unmarshal(out, &rows) != nil {
		return nil
	}
	var subs []Subnet
	for _, r := range rows {
		if r.Scope != "link" || !strings.Contains(r.Dst, "/") || r.Dev == "" {
			continue
		}
		if _, err := netip.ParsePrefix(r.Dst); err != nil {
			continue
		}
		subs = append(subs, Subnet{CIDR: r.Dst, Iface: r.Dev})
	}
	return subs
}

// Randomized reports whether a MAC has the locally-administered bit set —
// the second nibble is 2, 6, A or E. Phones rotate these per network, so the
// same device reappears as a new unknown host after a reset.
func Randomized(mac string) bool {
	if len(mac) < 2 {
		return false
	}
	b, ok := hexNibble(mac[1])
	return ok && b&0x2 != 0
}

func hexNibble(c byte) (byte, bool) {
	switch {
	case c >= '0' && c <= '9':
		return c - '0', true
	case c >= 'a' && c <= 'f':
		return c - 'a' + 10, true
	case c >= 'A' && c <= 'F':
		return c - 'A' + 10, true
	}
	return 0, false
}

// Vendors maps a 6-hex-digit uppercase OUI prefix to a short label.
type Vendors map[string]string

// LoadVendors decodes the embedded table. userDir may hold a lan.toml whose
// [names] section overrides a device label by MAC or IP; those are returned
// separately because they key on the whole address, not the prefix.
func LoadVendors(userDir string) (Vendors, map[string]string, error) {
	v := Vendors{}
	r := csv.NewReader(bytes.NewReader(ouiCSV))
	r.Comment = '#'
	r.FieldsPerRecord = 2
	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			continue // one bad row never drops the rest
		}
		v[strings.ToUpper(rec[0])] = rec[1]
	}
	names := map[string]string{}
	if userDir == "" {
		return v, names, nil
	}
	b, err := os.ReadFile(filepath.Join(userDir, "lan.toml"))
	if err != nil {
		return v, names, nil // absent is the normal case
	}
	var u struct {
		Names map[string]string `toml:"names"`
	}
	if _, err := toml.Decode(string(b), &u); err != nil {
		return v, names, err
	}
	for k, name := range u.Names {
		names[strings.ToLower(k)] = name
	}
	return v, names, nil
}

// Lookup returns the vendor for a MAC, or "" when the prefix is unknown.
func (v Vendors) Lookup(mac string) string {
	h := strings.ToUpper(strings.NewReplacer(":", "", "-", "").Replace(mac))
	if len(h) < 6 {
		return ""
	}
	return v[h[:6]]
}

// Fold collapses the neighbor table into one Host per device. A device
// answers on one MAC from several addresses — an IPv4 plus its EUI-64
// link-local, or the same address seen from two NICs on one segment — and
// those are one row.
//
// Distinct global IPv4 addresses on a shared MAC stay separate rows: that is
// a proxy-ARP router or a bridge answering for the boxes behind it, and
// folding three set-top boxes into one line would hide two of them. They are
// marked Shared instead.
func Fold(ns []Neighbor) []Host {
	type bucket struct {
		hosts []*Host
		other []Neighbor // link-locals and IPv6, attached after
	}
	buckets := map[string]*bucket{}
	var order []string
	for _, n := range ns {
		key := n.MAC
		if key == "" {
			key = "ip:" + n.IP
		}
		b, ok := buckets[key]
		if !ok {
			b = &bucket{}
			buckets[key], order = b, append(order, key)
		}
		if !globalV4(n.IP) {
			b.other = append(b.other, n)
			continue
		}
		if h := findIP(b.hosts, n.IP); h != nil {
			if better(n.State, h.State) {
				h.State = n.State
			}
			continue
		}
		b.hosts = append(b.hosts, &Host{
			MAC: n.MAC, IP: n.IP, Iface: n.Iface, State: n.State,
			Random: Randomized(n.MAC), Virtual: VirtualIface(n.Iface),
		})
	}

	var hosts []Host
	for _, k := range order {
		b := buckets[k]
		for _, n := range b.other {
			// No IPv4 for this MAC: the address itself is the device.
			if len(b.hosts) == 0 {
				b.hosts = append(b.hosts, &Host{
					MAC: n.MAC, IP: n.IP, Iface: n.Iface, State: n.State,
					Random: Randomized(n.MAC), Virtual: VirtualIface(n.Iface),
				})
				continue
			}
			h := b.hosts[0]
			if better(n.State, h.State) {
				h.State = n.State
			}
			if n.IP != h.IP && !slices.Contains(h.Extra, n.IP) {
				h.Extra = append(h.Extra, n.IP)
			}
		}
		for _, h := range b.hosts {
			h.Shared = len(b.hosts) > 1
			slices.Sort(h.Extra)
			hosts = append(hosts, *h)
		}
	}
	return hosts
}

func findIP(hs []*Host, ip string) *Host {
	for _, h := range hs {
		if h.IP == ip {
			return h
		}
	}
	return nil
}

// globalV4 is true for an IPv4 address that names a device on the segment,
// as opposed to a link-local the kernel derived from the same MAC.
func globalV4(ip string) bool {
	a, err := netip.ParseAddr(ip)
	return err == nil && a.Is4() && !a.IsLinkLocalUnicast()
}

// VirtualIface reports whether a neighbor was reached over something the
// kernel made up rather than a NIC. Their MACs are synthetic, so the
// locally-administered bit says "container", not "phone with MAC rotation".
func VirtualIface(name string) bool {
	for _, p := range []string{"docker", "br-", "veth", "virbr", "wg", "tailscale", "tun", "tap", "lo", "cni", "flannel", "podman"} {
		if strings.HasPrefix(name, p) {
			return true
		}
	}
	return name == "bridge"
}

// stateRank orders neighbor states best to worst; a device reachable on one
// interface is reachable, whatever the other interface last saw.
var stateRank = map[string]int{
	"reachable": 0, "permanent": 1, "noarp": 2, "delay": 3, "probe": 4,
	"stale": 5, "incomplete": 6, "failed": 7, "none": 8, "": 9,
}

func better(a, b string) bool { return rank(a) < rank(b) }

func rank(s string) int {
	if r, ok := stateRank[s]; ok {
		return r
	}
	return len(stateRank)
}

// Annotate fills in subnet, vendor, user name and gateway. Hosts outside every
// on-link CIDR keep an empty Subnet and group under their interface.
func Annotate(hosts []Host, subs []Subnet, v Vendors, names map[string]string, gateway string) {
	for i := range hosts {
		h := &hosts[i]
		h.Vendor = v.Lookup(h.MAC)
		if n, ok := names[h.MAC]; ok {
			h.Name = n
		} else if n, ok := names[h.IP]; ok {
			h.Name = n
		}
		h.Gateway = gateway != "" && h.IP == gateway
		h.Subnet = subnetOf(h.IP, subs)
	}
	slices.SortStableFunc(hosts, func(a, b Host) int { return compareHost(a, b) })
}

func subnetOf(ip string, subs []Subnet) string {
	addr, err := netip.ParseAddr(ip)
	if err != nil {
		return ""
	}
	best := ""
	bestBits := -1
	for _, s := range subs {
		p, err := netip.ParsePrefix(s.CIDR)
		if err != nil || !p.Contains(addr) {
			continue
		}
		if p.Bits() > bestBits { // most specific wins
			best, bestBits = s.CIDR, p.Bits()
		}
	}
	return best
}

// compareHost sorts the gateway first, then by address within a subnet.
func compareHost(a, b Host) int {
	if a.Gateway != b.Gateway {
		if a.Gateway {
			return -1
		}
		return 1
	}
	x, err1 := netip.ParseAddr(a.IP)
	y, err2 := netip.ParseAddr(b.IP)
	if err1 != nil || err2 != nil {
		return strings.Compare(a.IP, b.IP)
	}
	return x.Compare(y)
}

// AttachPeers marks which hosts this box is actually talking to, from the
// socket table the ports module already reads. Direction comes from the
// listening set, not from the port number: an NFS client dials out from a
// reserved port below 1024, so "low local port means inbound" is wrong on
// any box that mounts a share.
func AttachPeers(hosts []Host, es []ports.Established, listening map[int]bool) {
	in, out := map[string][]int{}, map[string][]int{}
	for _, e := range es {
		ap, err := netip.ParseAddrPort(e.Remote)
		if err != nil {
			continue
		}
		ip := ap.Addr().Unmap().WithZone("").String()
		if listening[e.LocalPort] {
			in[ip] = appendPort(in[ip], e.LocalPort)
		} else {
			out[ip] = appendPort(out[ip], int(ap.Port()))
		}
	}
	for i := range hosts {
		h := &hosts[i]
		for _, ip := range append([]string{h.IP}, h.Extra...) {
			for _, p := range in[ip] {
				h.In = appendPort(h.In, p)
			}
			for _, p := range out[ip] {
				h.Out = appendPort(h.Out, p)
			}
		}
		slices.Sort(h.In)
		slices.Sort(h.Out)
	}
}

// ListeningPorts is the set of local ports with a listener, from `ss -tulnH`.
func ListeningPorts(out []byte) map[int]bool {
	set := map[int]bool{}
	for _, l := range ports.ParseListeners(out) {
		set[l.Port] = true
	}
	return set
}

func appendPort(ps []int, p int) []int {
	if slices.Contains(ps, p) {
		return ps
	}
	return append(ps, p)
}
