#!/usr/bin/env python3
"""Generate internal/modules/lan/oui.csv from the IEEE MA-L registry.

The full registry is 34k organisations and 3MB; almost all of it is industrial
kit that never appears on a home or lab LAN. VENDORS below is the allowlist:
a regex over the IEEE organisation name mapped to the short label sitrep shows.
Every OUI belonging to a matched organisation is emitted, so a vendor with 800
prefixes (Apple, Samsung) is fully covered.

Usage: scripts/gen-oui.py [/usr/share/ieee-data/oui.csv] > internal/modules/lan/oui.csv
Refresh: apt install ieee-data, or curl https://standards-oui.ieee.org/oui/oui.csv
"""
import csv, re, sys

# regex (case-insensitive, matched against the IEEE org name) -> label
VENDORS = [
    (r"^Apple\b", "Apple"),
    (r"^Samsung\b", "Samsung"),
    (r"^Google\b|^Google, Inc", "Google"),
    (r"^Amazon\b|^Amazon Technologies", "Amazon"),
    (r"^Intel\b", "Intel"),
    (r"^Dell\b", "Dell"),
    (r"^Hewlett[ -]?Packard|^HP Inc|^HPE\b", "HP"),
    (r"^ASUSTek\b|^ASUS\b", "ASUSTek"),
    (r"^Belkin\b", "Belkin"),
    (r"^TP-LINK\b|^Tp-Link\b", "TP-Link"),
    (r"^NETGEAR\b", "Netgear"),
    (r"^Linksys\b|^Cisco-Linksys", "Linksys"),
    (r"^D-Link\b", "D-Link"),
    (r"^Ubiquiti\b", "Ubiquiti"),
    (r"^Mikrotik\b|^MikroTik\b", "MikroTik"),
    (r"^Cisco\b", "Cisco"),
    (r"^Aruba\b|^ARUBA\b", "Aruba"),
    (r"^Ruckus\b", "Ruckus"),
    (r"^GL Technologies|^GL\.iNet", "GL.iNet"),
    (r"^Espressif\b", "Espressif"),
    (r"^Raspberry Pi\b", "Raspberry Pi"),
    (r"^Texas Instruments\b", "TI"),
    (r"^Broadcom\b", "Broadcom"),
    (r"^Realtek\b", "Realtek"),
    (r"^Qualcomm\b", "Qualcomm"),
    (r"^MediaTek\b|^MEDIATEK\b", "MediaTek"),
    (r"^Microsoft\b", "Microsoft"),
    (r"^Sony\b", "Sony"),
    (r"^LG Electronics|^LG Innotek|^LGE\b", "LG"),
    (r"^Panasonic\b", "Panasonic"),
    (r"^Nintendo\b", "Nintendo"),
    (r"^Roku\b", "Roku"),
    (r"^Sonos\b", "Sonos"),
    (r"^Bose\b", "Bose"),
    (r"^ecobee\b", "ecobee"),
    (r"^Nest Labs", "Nest"),
    (r"^Ring LLC|^Ring Inc", "Ring"),
    (r"^Wyze\b", "Wyze"),
    (r"^TiVo\b", "TiVo"),
    (r"^Wistron Neweb", "Wistron Neweb"),
    (r"^ARRIS\b|^Arris\b", "Arris"),
    (r"^Technicolor\b|^Thomson Telecom", "Technicolor"),
    (r"^Actiontec\b", "Actiontec"),
    (r"^Zyxel\b|^ZyXEL\b", "Zyxel"),
    (r"^Huawei\b|^HUAWEI\b", "Huawei"),
    (r"^Xiaomi\b|^XIAOMI\b", "Xiaomi"),
    (r"^OnePlus\b", "OnePlus"),
    (r"^Motorola\b", "Motorola"),
    (r"^Nokia\b", "Nokia"),
    (r"^HTC\b", "HTC"),
    (r"^Lenovo\b", "Lenovo"),
    (r"^Acer\b", "Acer"),
    (r"^ASRock\b", "ASRock"),
    (r"^GIGA-BYTE|^Gigabyte\b", "Gigabyte"),
    (r"^Micro-Star\b|^MSI\b", "MSI"),
    (r"^Super Micro\b", "Supermicro"),
    (r"^QNAP\b", "QNAP"),
    (r"^Synology\b", "Synology"),
    (r"^Western Digital", "WD"),
    (r"^Seagate\b", "Seagate"),
    (r"^BUFFALO\b|^Buffalo\b", "Buffalo"),
    (r"^Brother\b", "Brother"),
    (r"^Canon\b", "Canon"),
    (r"^Seiko Epson|^EPSON\b", "Epson"),
    (r"^Xerox\b", "Xerox"),
    (r"^Prusa\b", "Prusa"),
    (r"^Ultimaker\b", "Ultimaker"),
    (r"^Grandstream\b", "Grandstream"),
    (r"^Polycom\b", "Polycom"),
    (r"^Yealink\b", "Yealink"),
    (r"^Obihai\b", "Obihai"),
    (r"^Philips\b|^Signify\b", "Philips"),
    (r"^IKEA\b", "IKEA"),
    (r"^Tuya\b", "Tuya"),
    (r"^Shelly\b|^Allterco\b", "Shelly"),
    (r"^Sonoff\b|^Shenzhen Coolkit", "Sonoff"),
    (r"^Lutron\b", "Lutron"),
    (r"^Honeywell\b", "Honeywell"),
    (r"^Chamberlain\b", "Chamberlain"),
    (r"^VMware\b", "VMware"),
    (r"^Oracle\b", "VirtualBox"),
    (r"^Xensource\b", "Xen"),
    (r"^Parallels\b", "Parallels"),
    (r"^Red Hat\b", "KVM"),
    (r"^PCS Systemtechnik", "VirtualBox"),
    (r"^Sagemcom\b", "Sagemcom"),
    (r"^AVM\b|^AVM GmbH", "AVM"),
    (r"^Google Fiber", "Google Fiber"),
    (r"^eero\b", "eero"),
    (r"^Amcrest\b", "Amcrest"),
    (r"^Hangzhou Hikvision", "Hikvision"),
    (r"^Dahua\b", "Dahua"),
    (r"^Reolink\b", "Reolink"),
    (r"^Axis Communications", "Axis"),
    (r"^Garmin\b", "Garmin"),
    (r"^Fitbit\b", "Fitbit"),
    (r"^GoPro\b", "GoPro"),
    (r"^DJI\b|^SZ DJI", "DJI"),
    (r"^Tesla\b", "Tesla"),
    (r"^Rivian\b", "Rivian"),
    (r"^Roborock\b|^Beijing Roborock", "Roborock"),
    (r"^iRobot\b", "iRobot"),
    (r"^Wiz\b|^WiZ\b", "WiZ"),
    (r"^Vizio\b|^VIZIO\b", "Vizio"),
    (r"^TCL\b", "TCL"),
    (r"^Hisense\b", "Hisense"),
    (r"^Sharp\b", "Sharp"),
    (r"^Toshiba\b", "Toshiba"),
    (r"^Fujitsu\b", "Fujitsu"),
    (r"^NEC\b", "NEC"),
    (r"^Ricoh\b", "Ricoh"),
    (r"^Kyocera\b", "Kyocera"),
    (r"^Zebra Technologies", "Zebra"),
    (r"^Juniper\b", "Juniper"),
    (r"^Extreme Networks|^Enterasys\b", "Extreme"),
    (r"^Fortinet\b", "Fortinet"),
    (r"^PALO ALTO NETWORKS|^Palo Alto Networks", "Palo Alto"),
    (r"^WatchGuard\b", "WatchGuard"),
    (r"^SonicWall\b|^Dell SonicWALL", "SonicWall"),
    (r"^Netronix\b", "Netronix"),
    (r"^Sercomm\b", "Sercomm"),
    (r"^Askey\b", "Askey"),
    (r"^Compal\b", "Compal"),
    (r"^Quanta\b", "Quanta"),
    (r"^Pegatron\b", "Pegatron"),
    (r"^Wistron\b", "Wistron"),
    (r"^Foxconn\b|^Hon Hai", "Foxconn"),
    (r"^Liteon\b|^LITE-ON\b", "Liteon"),
    (r"^Azurewave\b|^AzureWave\b", "AzureWave"),
    (r"^Murata\b", "Murata"),
    (r"^Silicon Labs|^Silicon Laboratories", "Silicon Labs"),
    (r"^Nordic Semiconductor", "Nordic"),
    (r"^Microchip Technology|^Atmel\b", "Microchip"),
    (r"^STMicroelectronics", "STMicro"),
    (r"^NXP\b", "NXP"),
    (r"^Marvell\b", "Marvell"),
    (r"^Aquantia\b", "Aquantia"),
    (r"^Mellanox\b", "Mellanox"),
    (r"^Chelsio\b", "Chelsio"),
    (r"^Emulex\b", "Emulex"),
    (r"^QLogic\b", "QLogic"),
    (r"^3Com\b", "3Com"),
    (r"^Ericsson\b", "Ericsson"),
    (r"^ZTE\b", "ZTE"),
    (r"^Vantiva\b", "Vantiva"),
    (r"^CommScope\b", "CommScope"),
    (r"^Calix\b", "Calix"),
    (r"^Adtran\b", "Adtran"),
    (r"^Ciena\b", "Ciena"),
    (r"^Sophos\b", "Sophos"),
    (r"^Netgate\b", "Netgate"),
    (r"^PC Engines", "PC Engines"),
    (r"^Protectli\b", "Protectli"),
    (r"^Beelink\b|^Shenzhen AZW", "Beelink"),
    (r"^Hardkernel\b", "Hardkernel"),
    (r"^Pine64\b|^PINE64\b", "Pine64"),
    (r"^Radxa\b", "Radxa"),
    (r"^SolidRun\b", "SolidRun"),
    (r"^BeagleBoard\b", "BeagleBoard"),
    (r"^Arduino\b", "Arduino"),
    (r"^Particle Industries", "Particle"),
    (r"^Ecovacs\b", "Ecovacs"),
    (r"^Anker\b|^Anker Innovations", "Anker"),
    (r"^Eufy\b", "Eufy"),
    (r"^SimpliSafe\b", "SimpliSafe"),
    (r"^ADT\b", "ADT"),
    (r"^Resideo\b", "Resideo"),
    (r"^Emerson\b", "Emerson"),
    (r"^Rachio\b", "Rachio"),
    (r"^Hunter Industries", "Hunter"),
    (r"^Sengled\b", "Sengled"),
    (r"^LIFX\b|^LiFi Labs", "LIFX"),
    (r"^Nanoleaf\b", "Nanoleaf"),
    (r"^Govee\b|^Shenzhen Intellirocks", "Govee"),
    (r"^Meross\b", "Meross"),
    (r"^Kasa\b", "Kasa"),
    (r"^Wemo\b", "Wemo"),
    (r"^Aqara\b|^Lumi United", "Aqara"),
    (r"^SmartThings\b", "SmartThings"),
    (r"^Ubee\b", "Ubee"),
    (r"^Hitron\b", "Hitron"),
    (r"^Motorola Mobility", "Motorola"),
    (r"^DIRECTV\b|^DirecTV\b", "DirecTV"),
    (r"^EchoStar\b|^Dish Network", "Dish"),
    (r"^Comcast\b", "Comcast"),
    (r"^Charter\b", "Charter"),
    (r"^Verizon\b", "Verizon"),
    (r"^AT&T\b", "AT&T"),
    (r"^Plume Design", "Plume"),
    (r"^Sagem\b", "Sagem"),
    (r"^Humax\b", "Humax"),
    (r"^Skyworth\b", "Skyworth"),
    (r"^Sichuan AI-Link|^Amlogic\b", "Amlogic"),
    (r"^Rockchip\b", "Rockchip"),
    (r"^Allwinner\b", "Allwinner"),
    (r"^Ralink\b", "Ralink"),
    (r"^Atheros\b", "Atheros"),
    (r"^Edimax\b", "Edimax"),
    (r"^Tenda\b|^Shenzhen Tenda", "Tenda"),
    (r"^Totolink\b", "Totolink"),
    (r"^Wavlink\b", "Wavlink"),
    (r"^Trendnet\b|^TRENDnet\b", "TRENDnet"),
]
COMPILED = [(re.compile(p, re.I), n) for p, n in VENDORS]

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/ieee-data/oui.csv"
    out = {}
    with open(src, newline="", encoding="utf-8", errors="replace") as f:
        for row in csv.DictReader(f):
            org = (row.get("Organization Name") or "").strip()
            asn = (row.get("Assignment") or "").strip().upper()
            if len(asn) != 6:
                continue
            for rx, label in COMPILED:
                if rx.search(org):
                    out[asn] = label
                    break
    print("# Generated by scripts/gen-oui.py from the IEEE MA-L registry. Do not edit.")
    print("# prefix,vendor")
    for k in sorted(out):
        print(f"{k},{out[k]}")

if __name__ == "__main__":
    main()
